version: "3.8"

services:
  clients-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@db-clients:3306/clients_db
    depends_on:
      - db-clients
    networks:
      - payetonkawa-network

  db-clients:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=clients_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - clients_data:/var/lib/mysql
    networks:
      - payetonkawa-network

networks:
  payetonkawa-network:
    driver: bridge

volumes:
  clients_data:
